### ISSUE TITLE
Exception not handled if configuration get() fails

### ISSUE THREAD

**Issue by rudolfl** [culturekings/afterpay#31]
It seems that exception is not handled if configuration call fails (due to bad secret in my case). (or I am doing something very wrong)

Consider code:
$authorization = new \CultureKings\Afterpay\Model\Merchant\Authorization(
    \CultureKings\Afterpay\Model\Merchant\Authorization::SANDBOX_URI,
    MERCHANT_ID,
    INCORRECT_MERCHANT_KEY
);

try {
    $configuration = \CultureKings\Afterpay\Factory\MerchantApi::configuration($authorization)->get();
}
catch (\CultureKings\Afterpay\Exception\ApiException $e)
{
    echo $e->getErrorResponse();
}

Result is:
Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://api-sandbox.secure-afterpay.com.au/v1/configuration` resulted in a `401 Unauthorized` response:
{
  "errorCode" : "unauthorized",
  "errorId" : "5c900b916afc7f5a",
  "message" : "Credentials are required to access th (truncated...)
' in /home/hatsfrom/new-hats/afterpay/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /home/hatsfrom/new-hats/afterpay/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/hatsfrom/new-hats/afterpay/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/hatsfrom/new-hats/afterpay/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/hatsfrom/new-hats/afterpay/vendor/guzzl in /home/hatsfrom/new-hats/afterpay/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111

**Comment by jared-fraser** [comment]
Thanks for the report. fixed in [#bc99df2e](https://github.com/culturekings/afterpay/commit/bc99df2ef8dafc7e64a0206ab86b86e71d30a8b4) and tagged as v2.2.0
